### PR TITLE
COSMIT: PEP8 and simplification of some python code

### PR DESCRIPTION
**Pull request by glemaitre**
Couple of enhancements regarding Python style. Let see if I did not break the CI.

### CODE REVIEW

**Comment by maxrousseau** [comment]
I made a modifications to the fetcher and changed the test images. The CI should work now if you can grab the latest 2 commits from my branch.

**Comment by glemaitre** [comment]
This is probably difficult to review but I did the following thing:

- Use pytest for the testing
- Report the coverage
- Include the image samples in the packages at install
- Create a proper command line `pfla` instead of the hack with `bin/pfla`
- Make some fetcher for the XML and DAT files.
- Include the XML file in the package.
- Clean up the usage of the `os.path.join`

and probaly some other stuff

**Comment by maxrousseau** [comment]
Great, the CI passed!! Thank you. Can I merge?

**Comment by glemaitre** [comment]
Let me check if I can cache the miniconda install. It will avoid rebuilding `shapes` everytime. It should be almost there :)

**Comment by maxrousseau** [comment]
Perfect let me know when you are ready!

**Comment by glemaitre** [comment]
Could you clear the cache on Travis: https://docs.travis-ci.com/user/caching/#clearing-caches
I think that the cache is outdated with some missing package but I don't have access to it.

**Comment by glemaitre** [comment]
Once done let me know, I can trigger again a build.

**Comment by maxrousseau** [comment]
Ok I have just cleared the cache. Edit: sorry for the delay.

**Comment by maxrousseau** [comment]
I cleared the caches once more

**Comment by glemaitre** [comment]
I modified the script. It should work now.

**Comment by maxrousseau** [comment]
Awesome! Thank you, I will merge now.

**Pull request merged**
